name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd sw-ui-lib
          npm install

      - name: Export new components & extract component meta data into JS
        run: |
          cd sw-ui-lib
          node add-component.js

      - name: Extract component meta data into JS
        run: |
          cd sw-ui-lib
          node generate-metadata.js
          
      - name: Start Server
        env:
          MONGO_STRING: ${{ secrets.MONGO_STRING }}
        run: |
          cd sw-ui-backend
          nohup node server.js &

      - name: Import meta-data to MongoDB
        env:
          MONGO_STRING: ${{ secrets.MONGO_STRING }}
        run: |
          cd sw-ui-lib
          node import-data.js

      - name: Install Angular CLI
        run: |
          npm install -g @angular/cli

      - name: Build library
        run: |
          cd sw-ui-lib
          ng build

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          cd sw-ui-lib
          git add .
          # Check if there are changes to commit
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "New Component added"
            git push --follow-tags origin main
          fi

      - name: Login to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: |
          cd sw-ui-lib/dist/sw-ui
          npm publish
